version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: hdmsfs23_k!vs
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "5041:80"
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - app-network

  weatherworker:
    build: 
      context: .
      dockerfile: WeatherWorker/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

  foodworker:
    build: 
      context: .
      dockerfile: FoodWorker/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    external: true