version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "5041:80"
      - "5042:443"
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - app-network

  weatherworker:
    build: 
      context: ./WeatherWorker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

  foodworker:
    build: 
      context: ./FoodWorker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    external: true